# -*- coding: utf-8 -*-
# vim: ft=yaml
---
driver:
  name: linode
  flavor: 2048

provisioner:
  name: salt_solo
  is_file_root: true
  salt_copy_filter:
    - .kitchen
    - .git
  state_top:
    base:
      "*":
        - test.mockup
        - kibana

platforms:
  - name: debian_jessie

suites:
  - name: default
    provisioner:
      pillars:
        top.sls:
          base:
            '*':
              - kibana
        kibana.sls:
          kibana:
            enabled: true

  - name: custom
    provisioner:
      pillars-from-files:
        kibana.sls: pillar_custom.sls
      pillars:
        top.sls:
          base:
            "*":
              - kibana
